package firebase

import com.riadmahi.firebase.core.FirebaseApp
import com.riadmahi.firebase.auth.FirebaseAuth
import com.riadmahi.firebase.firestore.FirebaseFirestore

/**
 * Firebase initialization for your KMP project.
 * Call [initialize] early in your app lifecycle.
 *
 * Generated by KFire CLI
 */
object FirebaseInit {

    private var initialized = false

    /**
     * Initialize Firebase. Call this once at app startup.
     *
     * - Android: Call in Application.onCreate() or MainActivity.onCreate()
     * - iOS: Call in AppDelegate or SwiftUI App init
     */
    fun initialize() {
        if (initialized) return
        
        // Initialize Firebase with default configuration
        // (uses google-services.json on Android, GoogleService-Info.plist on iOS)
        FirebaseApp.initialize()
        
        initialized = true
    }

    /**
     * Get the Firebase Auth instance.
     */
    val auth: FirebaseAuth
        get() {
            check(initialized) { "Call initialize() first" }
            return FirebaseAuth.getInstance()
        }

    /**
     * Get the Firestore instance.
     */
    val firestore: FirebaseFirestore
        get() {
            check(initialized) { "Call initialize() first" }
            return FirebaseFirestore.getInstance()
        }

}
