# Ce fichier doit être copié dans homebrew-kfire/.github/workflows/
name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          SHA256="${{ github.event.client_payload.sha256 }}"
          URL="${{ github.event.client_payload.url }}"

          # Update the formula
          sed -i "s|url \".*\"|url \"$URL\"|" Formula/kfire.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" Formula/kfire.rb

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/kfire.rb
          git commit -m "Update kfire to v${{ github.event.client_payload.version }}"
          git push
